const SMILE: string[] = ["Remember to smile"];

const Freedom_is_Worth_The_Fight: string[] = [
  "Opened eyes",
  "now take a breath",
  "A living miracle",
  "with limited moments left",
  "A beating heart",
  "Strong yet tender",
  "Designed to beat",
  "Not premature surrender",
  "I don't choose my start",
  "But I embrace the journey",
  "To light the world",
  "Though things may hurt me",
  "Not all knowing",
  "But strong to learn",
  "Always growing",
  "Through scars and burns",
  "I'll never 'arrive'",
  "And I'll never be perfect",
  "I'll make mistakes",
  "But doesn't mean I'm worthless",
  "I'm gifted life",
  "And called to freedom",
  "Meant to see the clouds",
  "And rise above them",
  "Oooooooh oh ooooh The story of my life",
  "Endure, learn fight and rise",
  "With courage that cuts the night",
  "Nooooo oh ooooh",
  "There no rest in sight",
  "If I sell my day for night",
  "So Freedom's worth the fight",
  "If the world we live in starts going crazy",
  "Will we be standing tall though walls are caving?",
  "When hope is blurred and light seems fading",
  "When right is wrong and truth's called hating",
  "Under the weight of trial may we not crumble",
  "Keep pressing on though at times we stumble",
  "When knees are weak may our hearts hold strength",
  "Because at the end of night",
  "The day starts again",
  "I won't bow my knee",
  "I won't change my course",
  "I won't sell my wings",
  "I won't drop my torch",
  "My futures bright",
  "And I'm called to more",
  "I won't turn my back",
  "and let it fade to black",
  "Oooooooh oh ooooh",
  "The story of my life",
  "Endure, learn fight and rise",
  "With courage that cuts the night",
  "Nooooo oh ooooh",
  "There no rest in sight",
  "If I sell my day for night",
  "So Freedom's worth the fight",
  "Oooooooh oh ooooh",
  "The story of my life",
  "Endure, learn fight and rise",
  "With courage that cuts the night",
  "Nooooo oh ooooh",
  "There no rest in sight",
  "If I sell my day for night",
  "So Freedom's worth the fight",
  "Amidst the craziness do not lose sight of who you are… don't lose sight of your visions, dreams, potential and purpose.",
  "Life has always been a fleeting gift… Embrace each and every moment of that gift.",
  "Do not surrender.Dare to live to the fullest and dream to the fullest. Dare to embrace each day with optimism, hope and faith… knowing THE BEST IS YET TO COME.",
  "No government or system can ever take that from you.",
];
const advice1: string[] = [
  "1. Have a firm handshake.",
  "A firm handshake is necessary in life for making a great first impression on everyone you meet.",
  "2. Look people in the eye.",
  "Looking people in the eye establishes a great connection with the person on the other end. It shows you're serious, enthusiast, listening, and actually want to have the conversation. Build your self-confidence, and build others' confidence in you.",
  "3. Sing in the shower.",
  "Change your mood and inspire positivity. Have a good sing in the shower.",
  "4. Own a great stereo system.",
  "Music is one of the biggest influences on our emotions. It lifts your spirits, motivates you and contributes to your overall mood and happiness.",
  "5. Keep secrets.",
  "You'll gain other people's trust by keeping secrets. It ensures that you won't harm anyone else's feelings.",
  "6. Never give up on anybody.",
  "If you find yourself in a tough situation with someone you care about, don't give up. Put in the effort and have patience. Miracles happen every day.",
  "7. Always accept an outstretched hand.",
  "We all need help in life. We can't do everything on our own even if we think we can. If someone offers to help you, kindly accept. Don't refuse.",
  "8. Be brave. Even if you're not, pretend to be. No one can tell the difference.",
  "Life favours the brave. Be brave. Don't let people see fear inside of you. They'll eat you alive.",
  "9. Whistle.",
  "Whistling is another form of “momentary musical performing”, alongside singing in the shower, and humming while you do the housework, likely reflecting our mood and chosen to enhance it.",
  "10. Avoid sarcastic remarks.",
  "Sarcasm is the lowest form of whit. You're not going to make anybody happy by being sarcastic all the time.",
  "11. Choose your life's mate carefully.",
  "From this one decision will come 90 per cent of all your happiness or misery.",
  "12. Make it a habit to do nice things for people who will never find out.",
  "Giving to others is an incredible feeling. There's some small thing everyday that can have a big impact on someone. Do nice things for people.",
  "13. Lend only those books you never care to see again.",
  "Books are a great source of knowledge no doubt, but more to the point, lend things that you don't mind not seeing again. Save yourself the frustration.",
  "14. Never deprive someone of hope; it might be all they have.",
  "Never tell people that they can't do something, or that their dreams are impossible. Hope is a beautiful thing. Avoid having a negative impact on someone's mind, no matter what it is they want to do.",
  "15. When playing games with children, let them win.",
  "Let children win the games you play with them. Allow children to feel happiness and the joy of triumph.",
  "16. Give people a second chance but not a third.",
  "Everybody makes mistakes. People are human and deserve a second chance. It no longer becomes an accidental mistake after a second chance. It becomes deliberate.",
  "17. Be romantic.",
  "If there's someone in your life that you care about, then show them. Be romantic for the ones you love. They'll appreciate it a lot.",
  "18. Become the most positive and enthusiastic person you know.",
  "Being positive not only adds to your own happiness, state of mind and success, but it also radiates that energy to the people you spend time around. It pays rich dividends.",
  "19. Loosen up. Relax. Except for rare life-and-death matters, nothing is as important as it first seems.",
  "Take it easy, try not to worry as much about situations that are not going to have a significant impact on your life.",
  "20. Don't allow the phone to interrupt important moments. It's there for our convenience, not the caller's.",
  "Often, people allow phone calls to distract them from cherish-able moments. Being present, managing time, and avoiding distractions are important life skills.",
  "21. Be a good loser.",
  "If someone is a good loser, they accept that they have lost a game or contest without complaining. Be humble in defeat, congratulate the winners, and let them have their celebration.",
  "22. Be a good winner.",
  "Be humble in victory, congratulate the losers on their great efforts.",
  "23. Think twice before burdening a friend with a secret.",
  "Secrets can be dangerous. Especially if you want the secret to remain a confidential.",
  "24. When someone hugs you, let them be the first to let go.",
  "A simple gesture, to show someone how much they mean to you.",
  "25. Be humble.",
  "A lot was accomplished before you were born.",
  "26. Don't burn bridges. You'll be surprised how many times you have to cross the same river.",
  "It is sometimes challenging to re-build bridges down the road. Be mindful of your decisions.",
  "27. Live your life so that your epitaph could read: No regrets.",
  "It has been said that you don't regret the things you did in life, you regret the things you did not. Do your best to live with no regrets.",
  "28. Be bold and courageous.",
  "When you look back on life, you'll regret the things you didn't do more than the ones you did.",
  "29. Never waste an opportunity to tell someone you love them.",
  "Telling the people you care about that you love them is such a simple gesture, with such a big impact.",
  "30. Remember no one makes it alone. Have a grateful heart and be quick to acknowledge those who helped you.",
  "Express gratitude directly to those who have helped you. Acknowledge them publicly. If someone has positively impacted your life, raise a glass and make a toast to honour their contribution.",
  "31. Take charge of your attitude. Don't let someone else choose it for you.",
  "Your attitude in life is crucial to your overall success and happiness. Don't let others have an influence on this for you. You control your attitude by controlling your thoughts.",
  "32. Visit friends and relatives when they are in the hospital; you only need to stay a few minutes.",
  "Just a few minutes of your day to see your relatives in hospital. You won't regret it.",
  "33. Begin each day with some of your favourite music.",
  "Studies have shown that what we hear within the first 20 minutes of waking up has a big effect on our mood for the rest of the day. Put some of your favourite music on.",
  "34. Once in a while, take the scenic route.",
  "So often we take the fastest route in life. Once in a while, take the scenic route and capture some of the raw beauty.",
  "35. Answer the phone with enthusiasm and energy in your voice.",
  "Always answer the phone with enthusiasm in your voice and show your appreciation for the caller.",
  "36. Keep a notepad and pencil on your bedside table. Million-dollar ideas sometimes strike at 3 a.m.",
  "This is incredibly true, and actually, Jay-Z used to carry a notepad with him everywhere he went.",
  "37. Show respect for everyone who works for a living, regardless of how trivial their job.",
  "People work hard. They deserve some respect.",
  "38. Send your loved ones flowers. Think of a reason later.",
  "There doesn't even need to be a reason to send your loved one's flowers. It's a nice surprise no matter what the reason may be.",
  "39. Make someone's day by paying the toll for the person in the car behind you.",
  "Another great example of having a positive effect on someone's day with very minimal effort.",
  "40. Become someone's hero.",
  "A hero is selfless, a genuinely good person, and someone gets the undivided attention of all of us and causes change. To the world you might think you are one person, but to one person you might be something bigger. Everybody needs a hero.",
  "41. Marry only for love.",
  "It's the only way to survive the challenges to come. The marriage will not last and it will leave you vulnerable.",
  "42. Count your blessings.",
  "Always be grateful for what you have in life. There are people out there who have far less than you, so always be grateful for that roof over your head, the job you have, the family you have, the food you eat.",
  "43. Compliment the meal when you're a guest in someone's home.",
  "If you're a guest in someone's house, and they cook for you, always be polite. Compliment the meal as a token of appreciation.",
  "44. Wave at the children on a school bus.",
  "Children love to smile and they love to wave. Waving back at children will make their day.",
  "45. Remember that 80% of the success in any job is based on your ability to deal with people.",
  "Every job involves dealing with other people in some way or another. Whether it be customers, employees, or other businesses. So if you haven't learned how, start now.",
  "46. Don't expect life to be fair.",
  "Life is not fair. Life is hard. Expect it to be that way. But that doesn't mean you can't achieve your dreams or goals. Never lose hope, work hard and have patience. If you can master these skills, what you want will come. It is only a matter of time.",
];
const advice2: string[] = [
  "Have a firm handshake.",
  "Look people in the eye.",
  "Sing in the shower.",
  "Own a great stereo system.",
  "If in a fight, hit first and hit hard.",
  "Keep secrets.",
  "Never give up in anybody. Miracles happen everyday.",
  "Always accept an outstretched hand.",
  "Be brave. Even if you're not, pretend to be. No one can tell the difference.",
  "Whistle.",
  "Avoid sarcastic remarks.",
  "Choose your life's mate carefully. From this one decision will come 90 percent of all your happiness or misery.",
  "Make it a habit to do nice things for people who will never find out.",
  "Lend only those books you never care to see again.",
  "Never deprive someone of hope; it might be all that they have.",
  "When playing games with children, let them win.",
  "Give people a second chance, but not a third",
  "Be romantic.",
  "Become the most positive and enthusiastic person you know.",
  "Loosen up. Relax. Except for rare life-and-death matters, nothing is as it first seems.",
  "Don't allow the phone to interrupt important moments. It's there for our convenience, not the caller's.",
  "Be a good loser.",
  "Be a good winner.",
  "Think twice before burdening a friend with a secret.",
  "When someone hugs you, let them be the first to let go.",
  "Be modest. A lot was accomplished before you were born.]",
  "Keep it simple.",
  "Beware of the person who has nothing to lose.",
  "Don't burn bridges. You'll be surprised how many times you have to cross the same river.",
  "Live your life so that your epitaph could read, No Regrets.",
  "Be bold and courageous. When you look back on life, you'll regret the things you didn't do more than the ones you did.",
  "Never waste an opportunity to tell someone you love them.",
  "Remember no one makes it alone. Have a grateful heart and be quick to acknowledge those who helped you.",
  "Take charge of your attitude. Don't let someone else choose it for you.",
  "Visit friends and relatives when they are in hospital; you need only stay a few minutes.",
  "Begin each day with some of your favourite music.",
  "Once in a while, take the scenic route.",
  "Send a lot of valentine cards. Sign them. Someone who thinks you're terrific.'",
  "Answer the phone with enthusiasm and energy in your voice.",
  "Keep a note pad and pencil on your bed-side table. Million-dollar ideas sometimes strike at 3 a.m.",
  "Show respect for everyone who works for a living, regardless of how trivial their job.",
  "Send your loved ones flowers. This if a reason later.",
  "Make someone's day by paying the toll/coffee for the person in the car behind you.",
  "Become someone's hero.",
  "Marry only for love.",
  "Count your blessings.",
  "Compliment the meal when you're a guest in someone's home.",
  "Wave at the children on a school bus.",
  "Remember 80 percent of the success in any job is based on your ability to deal with people.",
  "Don't expect life to be fair.",
];
const advice3: string[] = [
  "Always maintain a good sense of humor.",
  "Never be too good to start at the bottom.",
  "Exercise every single day, even when you don't feel like it.",
  "Don't spend more money than you make.",
  "Drink orange juice every day.",
  "Love at first sight is not a fable.",
  "Having a bad job is better than having no job at all.",
  "Eat around the mold; don't go wasting food.",
  "Your family is the most precious thing you will ever have in life.",
  "Eat sausage every day - it worked for me.",
  "Your life is delicate, and if you neglect yourself, youll spoil. Thats what cheese taught me.",
  "Don't ever be afraid to be your true self.",
  "Everyone has too many clothes. Wear what you have and quit buying more.",
  "You must be able to forgive, even if its difficult to do.",
  "Save your money now and spend it later.",
  "Love is not always easy; sometimes you have to work at it.",
  "Find something comical in every single situation.",
  "If youre faced with a problem, don't delay trying to figure it out. But if theres no way to figure it out, you have to forget about it.",
  "Make sure youre doing what you love; don't be afraid to follow those dreams you have for yourself.",
  "Education is important, but not necessary. Life can be an education in itself.",
  "Explore your world and stay curious.",
  "Try not to take yourself so seriously.",
  'My full name is William Bradford James Anderson, and my initials always remind me to ask myself, "Why be just anybody?"',
  "Have common sense. Think about the most reasonable answer to every situation. If you don't have common sense, youre a bust.",
  "Life is a gift that you must unwrap. Its up to you to determine if whats inside will lead you to happiness or dismay. You have the power to make that decision for yourself.",
];
const al: string[] = [
  "1. He faces challenges head-on",
  "Alpha males bravely face every challenge life throws at them. In fact, they thrive when life throws them a curveball. They conquer their fears and insecurities and overcome all the obstacles. Even when the stakes are high, they don't stand down but strive. Failures are part of their life, too, but they are never get bogged down by them. They dust themselves off and try again.",
  "2. He makes tough decisions",
  "An alpha male has the ability to make tough decisions in high-pressure situations. He assesses the situation and decides the right thing to do. Once the decision is made, he doesn't agonize over it. He shows confidence in his judgment and avoids second-guessing himself.",
  "3. He is humble",
  "Alpha male is humbleSave",
  "Alpha men might reach new heights of success, but their feet are firmly on the ground. They feel happy about their achievements but are not arrogant about them. Bragging about their accomplishments is not their style. They are self-assured and don't need validation from others.",
  "4. He is fiercely determined",
  "Alpha men are go-getters. They work persistently towards their goals and never back down. Even if they stumble along the way, they get up and keep going. Quitting is not a part of their vocabulary. If they believe in something, they fight against all odds to find a way and remain motivated.",
  "Did you know?",
  "Alpha males love to take the lead in their relationships. They are incredibly loyal and committed to their companions.",
  "5. He is a thorough gentleman",
  "An alpha male is a thorough gentleman. He has a deep respect for women and appreciates them. It's in his nature to open doors, pull out chairs, give his seat to a woman, and see her to the door after a date. He listens when the woman is speaking and never cuts her off mid-sentence.",
  "6. He is a natural leader",
  "Alpha males are natural leaders. They take charge of the situation and lead from the front. People are inspired by them and tend to follow them. Alpha men generally occupy senior executive-level positions in top companies because of their leadership qualities. They empower people and work with them to achieve success.",
  "7. He is aware of his flaws",
  "A man is not just defined by his strengths but also by the way he handles his weaknesses. Alpha men know their weaknesses well. They do not try to hide them in any manner. Flaws do not handicap them; instead, they work towards overcoming them. Alpha men are known for turning their weaknesses into strengths.",
  "8. He is physically and mentally strong",
  "He always keeps his coolSave",
  "Health is wealth — Alpha men know this adage well and take utmost care of their health. They keep their body fit by working out and eating healthy. Their fitness is not limited just to their body; they are mentally strong as well. They keep their cool even in high-pressure situations.",
  "9. He is honest and upfront",
  "Alpha men are pretty upfront. This doesn't mean they are deliberately hurtful; they call a spade a spade even if it is painful. They are not afraid to tell the truth, even in the most tricky situations, and are strong enough to face the consequences. Alpha men believe in honestly and accept their mistakes even if it paints them in a less than favorable light.",
  "10. He manages his emotions well",
  "You need to have a good degree of emotional intelligence to connect well with people. Alpha men manage their emotions exceptionally well. In an emotionally charged situation, they think rationally instead of giving in to emotional outbursts. They are good at reading people's emotions and diffusing volatile situations by showing empathy.",
  "Play Video",
  "Related: How To Build An Emotional Connection With Your Partner?",
  "11. He is clear about his goals",
  "Alpha men are very clear about what they want in life. They work hard to achieve the goals they have set for themselves in their professional or personal lives. They make every decision and every move keeping the end purpose in mind. You will never find them living a purposeless life.",
  "12. He is particular about his appearance and posture",
  "Well-groomed people make a great first impression. Alpha men are very particular about how they present themselves. They maintain personal hygiene, wear good clothes, and make sure they look their best. They are confident individuals and use their body language to their advantage. Standing straight, keeping the chin up, proper eye contact, firm handshake — these come naturally to the alpha male while interacting with people.",
  "13. He is protective of loved ones",
  "He cares about people close to himSave",
  "Image: Shutterstock",
  "Real alpha men are not controlling but are fiercely protective of their loved ones. They care about people close to them and do everything in their power to keep these people safe. They don't enjoy fights but seeing their dear ones in pain and at risk might bring out their aggressive side.",
  "14. He has strong communication skills",
  "Alpha men are good with people. They share interesting stories and keep their audience thoroughly entertained. Their innate charisma pulls people in, and they speak with confidence and assertiveness, gaining people's trust. They also speak transparently and listen with interest when others talk.",
  "15. He has a great sense of humor",
  "One of the biggest strengths of an alpha male is his sense of humor. He doesn't get offended if people make fun of him. Instead, he spins the situation in his favor by laughing at himself. He can make light of even his most humiliating failure because he considers it a learning experience. A silly joke has no effect on his sense of self-worth — he takes it in his stride and wins the hearts of even his detractors.",
];

const advice4: string[] = [
  "Take risks in your life. If you win, you can lead; if you lose, you can guide.",
  "People are not what they say but what they do; so judge them not from their words but from their actions.",
  "When someone hurts you, don't feel bad because it's a law of nature that the tree that bears the sweetest fruits gets maximum number of stones.",
  "Take whatever you can from your life because when life starts taking from you, it takes even your last breath.",
  "In this world, people will always throw stones on the path of your success. It depends on what you make from them - a wall or a bridge.",
  "Challenges make life interesting; overcoming them make life meaningful.",
  "There is no joy in victory without running the risk of defeat.",
  "A path without obstacles leads nowhere.",
  "Past is a nice place to visit but certainly not a good place to stay.",
  "You can't have a better tomorrow if you are thinking about yesterday all the time.",
  "If what you did yesterday still looks big to you, then you haven't done much today.",
  "If you don't build your dreams, someone else will hire you to build theirs.",
  "If you don't climb the mountain; you can't view the plain.",
  "Don't leave it idle - use your brain.",
  "You are not paid for having brain, you are only rewarded for using it intelligently.",
  "It is not what you don't have that limits you; it is what you have but don't know how to use.",
  "What you fail to learn might teach you a lesson.",
  "The difference between a corrupt person and an honest person is: The corrupt person has a price while the honest person has a value.",
  "If you succeed in cheating someone, don't think that the person is a fool...... Realize that the person trusted you much more than you deserved.",
  "Honesty is an expensive gift; don't expect it from cheap people.",
];
const advice5: string[] = [
  "After a while, you get used to people understanding.",
  "Aspire to inspire before you expire.",
  "Bad? Nope. I'm the worst!",
  "Contrary to popular belief, I know exactly what I'm doing.",
  "Do I have a short temper? Nope. But I do have a quick reaction when it comes to bullsh*t",
  "Don't try to fit in. You were born to stand out.",
  "Even the galaxy is incomplete without me, 'coz I'm the main star.",
];
const ankur_warikoo_22_lessons: string[] = [
  "You can change your past by changing the meaning of your memories.",
  "The smarter you get, the faster you lose friends.",
  "Money doesn't chhange you. It amplifies who you truly are.",
  "You don't suck at managing your time, you just don't know how valuable it is.",
  "A beautiful life is to know how to live alone, but never have the need to.",
  "Your fear of embarrassing yourself, is your biggest hurdle to growth.",
  "No one is coming to save you. Your life is 100% your responsibility.",
  "The hardest thing is to focus. The easiest thing is to complain.",
  "You will free yourself the day you forgive your parents and stop blaming them.",
  "The more available you are, the less respected you'd be.",
  "If you truly know who you are, no one can ever touch you!",
  "The day you stop asking 'when should I do it', is the day you are ready to do it.",
  "We all have two money lives. The second one begains when we realize we have enough money for our life.",
  "If you say the truth, you do not have to remember what you said to whom.",
  "True grouth lies in doing the boring things over and over again.",
  "When in doubt don't ask what should I do. Instead ask what do I WANT to do. Solve for making that happen.",
  "If you aren't happy doing it, why are you still in it?",
  "Focus on effort, not results.",
  "If your parents are not rich, but you got a good education, be grateful fro their sacrifices.",
  "A truly happy person will never troll anyone.",
  "The face can be misleading. Fall in love with the mind.",
  "If you are loved only when you are around, then it's not love.",
  "The only thing that matters in the world is your opinion about your own.",
  "I trust you!",
];
export {
  Freedom_is_Worth_The_Fight,
  advice1,
  advice2,
  advice3,
  advice4,
  advice5,
  al,
  SMILE,
  ankur_warikoo_22_lessons,
};
